### ISSUE TITLE
[feature-request] lock text/rocket-shapes

### ISSUE THREAD

**Issue by ligi** [bleeptrack/cccamp19-generator#2]
First of all - this generator is great! 
Just one suggestion: It would be awesome if one can lock the text or rocket-shapes
Backgronund - was just trying to generate a svg for @chaos-infusion - but when doing so sometimes the text looked nice - but I did not like the rocket-shapes - or the other way around. It would be great to be able to either lock them or have 2 generator buttons (regenerate rockets, regenerate text)

**Comment by bleeptrack** [comment]
Nice idea, I'll try to implement that! Shouldn't be too hard to split the generation into two processes :)

**Comment by bleeptrack** [comment]
Implemented in commit 0c3d2fe5b838d6cf9ec6f956f48e960a28d54fb1 :)
